# required
filter_options:
  HOUSE: false
  UKF: false
  CUT4: false
  CUT6: false
  num_trials: 1

# requried
orbtial_parameters:
  # initial state of satillite (type ECEF or ECI)
  initial_state: [2540685.04200000,	-2210122.18300000,	6346730.16400000,	6797.93258150000,	274.414411400000,	-2588.42618040000]
  initial_state_type: ECI

  # ground station (as ECEF, velocities assumed to be 0)
  ground_station: [0, 0, 6378100.0, 0, 0, 0] # north pole

  # measurement error with units [metres, arcsec, arcsec]
  # current data from https://www.sciencedirect.com/science/article/abs/pii/S0273117722002496
  range_error: 100
  range_rate_error: 0.3
  azimuth_error: 100
  elevation_error: 100
  
  

  # time step in seconds, MJD in days
  time_step: 60
  MJD_start:  57569.9998032407 # 2010-JAN-04
  MJD_end:    57571.1241087963 #5.757212410879634e+4


# optional, if not defined they will be set to default values
propagator_settings:
  third_body_attraction: true
  third_body_sun: true
  third_body_moon: true
  solid_earth_tide: false
  ocean_tide_loading: false
  solar_radiation_pressure : true
  relativity_effect: true
  srpCoef: 1.23
  srpArea : 0.136488 # 2 * PI  * pow(0.974 / 2, 2) * sin(0) + 1.034 * 0.132
  satMass : 61.14

file_options:
  ERP_file: cof19037.erp
  gravity_file: GGMOS3.txt
  ephemeris_file: unxp2000.405
  # this directory must exist
  output_directory: out