
# requried
scenario_parameters:
  # time step in seconds, MJD in days
  time_step: 10
  # # time duration of each pass in seconds
  # time_pass: 120
  MJD_start: 59348.916238425903430 
  MJD_end: 59349.999571759297396
  # this directory must exist
  # output_directory: out
  output_directory: out/out_prop

# requried
initial_orbtial_parameters:
  dim_state: 6
  # initial state of satillite (type ECEF or ECI), unit: m, m/s
  initial_state: [-1049836.531406142516062,-4275236.478115282021463,-6337381.515492259524763,5944.446546185818079,2819.968620172394367,-2885.421064631562786]
  initial_state_type: ECI
  initial_covariance: 


# optional, if not defined they will be set to default values
propagator_truth_settings:
  third_body_attraction: true
  third_body_sun: true
  third_body_moon: true
  solid_earth_tide: true
  ocean_tide_loading: true
  solar_radiation_pressure : true
  atmospheric_drag: true
  relativity_effect: true
  srpCoef: 1.23
  srpArea : 8.73
  dragCoef: 2.0
  dragArea : 4.091655
  satMass : 961.831

# optional
supporting_files:
  gravity_file: ./auxdata/GGM03S.txt
  ephemeris_file: ./auxdata/unxp2000.405
  ERP_file: ./auxdata/cod21587.erp
