# required
filter_options:
  HOUSE: true
  UKF: false
  CUT4: false
  CUT6: false
  num_trials: 1

# requried
scenario_parameters:
  MJD_start: 59349.51137986922 # 2021-May-15
  # MJD_end:  59349.51140078588 # 2021-May-17
  # MJD_end:  59349.51288590162 # 2021-May-17
  MJD_end:  59351.54470621643 # 2021-May-17
  # MJD_start: 59349.51137986922 # 2021-May-15
  # MJD_end:  59349.51250939351
  max_time_step: 60
  # this directory must exist
  output_directory: out/out_ccdata

# requried
initial_orbtial_parameters:
  dim_state: 6
  # initial state of satillite (type ECEF or ECI), unit: m, m/s
  initial_state: [-3669575.62359752, 1040418.51432516,6705990.19621435,-5051.32766883,-4686.71761172,-2035.77367562] # initial condition from tle 
  # initial_state: [-3670344.7060020026,1040280.3902267866,6705782.195689557,-5051.439372019426,-4686.233409635222,-2035.9701596230573] # pod reference 
  # initial_state: [-4299182.037649778,424377.41311747686,6392328.627819218,-4602.143031060031,-4768.812901435728,-2776.03925579375]
  initial_state_type: MEE
  # initial_covariance: #Ref.: https://doi.org/10.2514/1.G006481
  initial_covariance: 
    - [1.0e+6, 0, 0, 0, 0, 0]
    - [0, 1.0e+4, 0, 0, 0, 0]
    - [0, 0, 4.0e+4, 0, 0, 0]
    - [0, 0, 0, 0.01, 0, 0]
    - [0, 0, 0, 0, 0.25, 0]
    - [0, 0, 0, 0, 0, 0.04]    
  process_noise_covariance:
    - [100, 0, 0, 0, 0, 0]
    - [0, 1.0e-10, 0, 0, 0, 0]
    - [0, 0, 1.0e-8, 0, 0, 0]
    - [0, 0, 0, 1.0e-9, 0, 0]
    - [0, 0, 0, 0, 1.0e-9, 0]
    - [0, 0, 0, 0, 0, 1.0e-9]

# requried
measurement_parameters:
  # measurement file
  meas_file: ccdata/meas_data_id_46984.csv
  # ground station (as ECEF, velocities assumed to be 0)
  ground_station: [-2730164.38085497, 3714370.03545681, 4393632.92952871, 0, 0, 0] #Jinlin, Jinlin, ECEF coordinate, unit: m, m/s
  dim_meas: 2
  # measurement error with units [arcsec, arcsec]
  right_ascension_error: 3
  declination_error: 3


# optional, if not defined they will be set to default values
propagator_filter_settings:
  third_body_attraction: true
  third_body_sun: true
  third_body_moon: true
  solid_earth_tide: true
  ocean_tide_loading: true
  solar_radiation_pressure : true
  atmospheric_drag: true
  relativity_effect: true
  srpCoef: 1.23
  srpArea : 8.73
  dragCoef: 2.0
  dragArea : 4.091655
  satMass : 961.831

# optional
supporting_files:
  gravity_file: ./auxdata/GGM03S.txt
  ephemeris_file: ./auxdata/unxp2000.405
  ERP_file: ./auxdata/cod21587.erp