filter_options:
  SRHOUSE: true
  HOUSE: true
  UKF: true
  CUT4: true
  CUT6: true
  delta: 0
  weight: -1.0
  num_trials: 100

simulation_parameters:
  time_step: 0.5
  total_step: 100  
  output_directory: out/out_lorenz

initial_state:
  state_dim: 5
  fvalue: 8.0
  initial_noise_std: 0.5 
  initial_noise_skew: 1.0 
  initial_noise_kurt: 30.0 

process_noise:  
  process_noise_std: 1.0e-6
  process_noise_skew: 1.0
  process_noise_kurt: 30.0

measurement_noise:
  measurement_dim: 1
  measurement_type: pearson
  measurement_std: 0.2
  measurement_skew: -1.0
  measurement_kurt: 30.0