# required
filter_options:
  square_root: false
  HOUSE: true
  UKF: true
  CUT4: false
  CUT6: false
  init_noise: true
  num_trials: 100

# requried
simulation_parameters:
  # time step in seconds, MJD in days
  time_step: 10
  # time duration of each pass in seconds
  time_pass: 120
  max_time_step: 10  
  MJD_start: 55200.0 # 2010-JAN-04
  MJD_end: 55200.2 #5.757212410879634e+4
  # this directory must exist
  # output_directory: out
  output_directory: out/out_sparse_pearson

# requried
initial_orbtial_parameters:
  dim_state: 6
  # initial state of satillite (type ECEF or ECI), unit: m, m/s
  initial_state: [7007.2175e+3, 0, 0, 0, 0.6606e+3, 7.5509e+3]
  initial_state_type: ECI
  initial_covariance: 
    - [1.0e+6, 0, 0, 0, 0, 0]
    - [0, 1.0e+4, 0, 0, 0, 0]
    - [0, 0, 4.0e+4, 0, 0, 0]
    - [0, 0, 0, 0.01, 0, 0]
    - [0, 0, 0, 0, 0.25, 0]
    - [0, 0, 0, 0, 0, 0.04] 
  initial_skewness: -1.6
  initial_kurtosis: 10     
  process_noise_covariance:
    - [4, 0, 0, 0, 0, 0]
    - [0, 4, 0, 0, 0, 0]
    - [0, 0, 4, 0, 0, 0]
    - [0, 0, 0, 0.0001, 0, 0]
    - [0, 0, 0, 0, 0.0001, 0]
    - [0, 0, 0, 0, 0, 0.0001]    

# requried
measurement_parameters:
  # ground station (as ECEF, velocities assumed to be 0)
  ground_station: [0, 0, 6378100.0, 0, 0, 0] # north pole
  dim_meas: 4
  # measurement error with units [metres, arcsec, arcsec]
  # current data from https://www.sciencedirect.com/science/article/abs/pii/S0273117722002496
  range_error: 30
  range_rate_error: 0.3
  azimuth_error: 100
  elevation_error: 100
  meas_skewness: [0.1, 0.1, 0.1, 0.1]
  meas_kurtosis: [6, 6, 6, 6]

# optional, if not defined they will be set to default values
propagator_truth_settings:
  earth_gravity_model_order: 100
  earth_gravity_model_degree: 100
  third_body_attraction: true
  third_body_sun: true
  third_body_moon: true
  solid_earth_tide: false
  ocean_tide_loading: false
  solar_radiation_pressure : true
  atmospheric_drag: true
  relativity_effect: true
  srpCoef: 1.23
  srpArea : 0.136488 # 2 * PI  * pow(0.974 / 2, 2) * sin(0) + 1.034 * 0.132
  satMass : 61.14

# optional, if not defined they will be set to default values
propagator_filter_settings:
  earth_gravity_model_order: 20
  earth_gravity_model_degree: 20
  third_body_attraction: false
  third_body_sun: false
  third_body_moon: false
  solid_earth_tide: false
  ocean_tide_loading: false
  solar_radiation_pressure : false
  atmospheric_drag: false
  relativity_effect: false
  srpCoef: 1.23
  srpArea : 0.136488 # 2 * PI  * pow(0.974 / 2, 2) * sin(0) + 1.034 * 0.132
  satMass : 61.14  